### ISSUE TITLE
PreRelease changes

### ISSUE THREAD

**Issue by andreilupu** [Codeinwp/themeisle-content-forms#13]
From Codeinwp/themeisle-companion#147

1. for newsletter form adds error label and render the form also.
2. improve fields/form settings order, based on the type of the theme.
3. Check repeatable fields for beaver.
4. Make username optional, user email as a username in case that username field is not.

**Comment by ineagu** [comment]
@selul @andreilupu 

we also talked about removing both the module listing + his settings: https://www.dropbox.com/s/45cr7ezze0pc2kb/Screenshot%202018-01-09%2016.38.45.png?dl=0.

The forms will be loaded when Elementor or beaver modules are active.

**Comment by selul** [comment]
@andreilupu one more thing related to the prelaunch, but in obfx: https://github.com/Codeinwp/themeisle-companion/issues/177

**Comment by andreilupu** [comment]
This is done, and there is a PR for it here https://github.com/Codeinwp/themeisle-companion/pull/179
