### ISSUE TITLE
auto-sync obfx elementor modules with EAW plugin

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/themeisle-content-forms#19]
cc @selul @andreilupu

**Comment by selul** [comment]
Im not sure what eaw means ?

**Comment by andreilupu** [comment]
Elementor Addon Widgets?

**Comment by ineagu** [comment]
yep

**Comment by ineagu** [comment]
right now @abaicus was doing copy/paste thing when a new eleemntor widget will be launched in orbitfox, we can review the logic and make sure every time to fix/add new widgets they will be in both plugins

**Comment by andreilupu** [comment]
I've moved the issue in EAW
