### ISSUE TITLE
"Invalid email" message without email field

### ISSUE THREAD

**Issue by radu-themeisle** [Codeinwp/themeisle-content-forms#26]
We got a couple of users reporting that even though they removed the email field from the Contact Form widget they get the error "Invalid email".
Here's a screenshot from local testing: http://prntscr.com/mwt76y

**Comment by contactashish13** [comment]
@radu-themeisle does it make sense for a contact form not to have email? Similar to my comment https://github.com/Codeinwp/themeisle-content-forms/pull/24#issuecomment-470094948 its not a contact form but a generic form if you remove email, name and message. What should the name and email say when an email is sent in such cases?

**Comment by radu-themeisle** [comment]
@contactashish13 in the context of a contact form no, it doesn't make sense to not have an email field.
Users might use it to gather some info, replies who knows (I'll ask the next time I see someone complaining).

But the issue is that regardless of that, it doesn't really make sense to show an error of a field which is not active, it's bad UX.
So either we eliminate it when there's no field (same for other field types), or we tell users on support that it doesn't make sense to not have those fields and risk them backfiring on us because they don't want to accept that answer 😒

**Comment by contactashish13** [comment]
@radu-themeisle yeah it would be good to know the use cases so that we can improve the UX. You can close this issue as this is related to #23 and will be handled as part of #24

**Comment by radu-themeisle** [comment]
Great, thank you very much @contactashish13 ! 🙂
