### ISSUE TITLE
Newsletter form error messages for incorrect key

### ISSUE THREAD

**Issue by radu-themeisle** [Codeinwp/themeisle-content-forms#30]
The newsletter throws a "null" error if you don't have Mailchimp properly setup: http://prntscr.com/n6y0cc
For SendinBlue it says "Key not found" and this seems to be ok: http://prntscr.com/n6y1sv

**Comment by contactashish13** [comment]
@radu-themeisle I'm unable to reproduce this. Here is what I get when I save the form with the mailchimp key as empty

![image](https://user-images.githubusercontent.com/12953439/56095235-32e0bb80-5ef8-11e9-8473-df590d96f4da.png)

**Comment by radu-themeisle** [comment]
I think it was sorted in the update and it's not relevant anymore. But if anything, I'll write it down here #23
