### ISSUE TITLE
Style tab not loading on demos

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/themeisle-content-forms#38]
It's loading randomly after some refreshes.
![Screenshot (4)](https://user-images.githubusercontent.com/3266155/61460224-f8fbd700-a976-11e9-8450-848c36f2e06d.png)

@Codeinwp/theme-dev considering this is having a big impact on the starter sites, and maybe Ash doesn't have enough time for it, we can also show some love to this and OBFX in general 💯 . This would be also useful to have https://github.com/Codeinwp/themeisle-content-forms/issues/36

**Comment by abaicus** [comment]
@rodica-andronache I can't seem to replicate this in any way. Not on the demo or locally. :(

**Comment by rodica-andronache** [comment]
@abaicus I've added you here https://demo.themeisle.com/neve-architecture/ where this is happening most of the times for me, maybe it would help

**Comment by cristian-ungureanu** [comment]
@abaicus I manage to replicate this in Hestia too. What I did was to import the woocommerce demo, then add the newsletter widget from obfx. I noticed this error console http://prntscr.com/oiaquw and the widgets from obfx look like this http://prntscr.com/oiary9 . If you can't replicate, I can investigate further.

**Comment by cristian-ungureanu** [comment]
The error appears when you switch the tabs and that editor.js is from elementor ( assets/js/editor.js )
